"""
Provides the MediaWiki API actions.
https://www.mediawiki.org/w/api.php?action=help
"""
from enum import Enum

class Action(str, Enum):
    """The MediaWiki API actions."""

    # Core Content Operations
    QUERY = "query"
    """Fetch data from and about MediaWiki."""
    EDIT = "edit"
    """Create and edit pages."""
    PARSE = "parse"
    """Parses content and returns parser output."""
    COMPARE = "compare"
    """Get the difference between two pages."""
    PURGE = "purge"
    """Purge the cache for the given titles."""
    MOVE = "move"
    """Move a page."""
    DELETE = "delete"
    """Delete a page."""
    UNDELETE = "undelete"
    """Undelete revisions of a deleted page."""
    PROTECT = "protect"
    """Change the protection level of a page."""
    REVISIONDELETE = "revisiondelete"
    """Delete and undelete revisions."""
    ROLLBACK = "rollback"
    """Undo the last edit to the page."""
    PATROL = "patrol"
    """Patrol a page or revision."""

    # Authentication & User Management
    CLIENTLOGIN = "clientlogin"
    """Log in to the wiki using the interactive flow."""
    LOGIN = "login"
    """Log in and get authentication cookies."""
    LOGOUT = "logout"
    """Log out and clear session data."""
    CREATEACCOUNT = "createaccount"
    """Create a new user account."""
    CHANGEAUTHENTICATIONDATA = "changeauthenticationdata"
    """Change authentication data for the current user."""
    REMOVEAUTHENTICATIONDATA = "removeauthenticationdata"
    """Remove authentication data for the current user."""
    LINKACCOUNT = "linkaccount"
    """Link an account from a third-party provider to the current user."""
    UNLINKACCOUNT = "unlinkaccount"
    """Remove a linked third-party account from the current user."""
    RESETPASSWORD = "resetpassword"
    """Send a password reset email to a user."""
    VALIDATEPASSWORD = "validatepassword"
    """Validate a password against the wiki's password policies."""

    # User Preferences & Settings
    OPTIONS = "options"
    """Change preferences of the current user."""
    GLOBALPREFERENCES = "globalpreferences"
    """Change global preferences of the current user."""
    GLOBALPREFERENCEOVERRIDES = "globalpreferenceoverrides"
    """Change local overrides for global preferences."""
    SETNOTIFICATIONTIMESTAMP = "setnotificationtimestamp"
    """Update the notification timestamp for watched pages."""
    CLEARHASMSG = "clearhasmsg"
    """Clears the hasmsg flag for the current user."""

    # User Rights & Blocking
    USERRIGHTS = "userrights"
    """Change a user's group membership."""
    GLOBALUSERRIGHTS = "globaluserrights"
    """Add/remove a user to/from global groups."""
    BLOCK = "block"
    """Block a user."""
    UNBLOCK = "unblock"
    """Unblock a user."""
    GLOBALBLOCK = "globalblock"
    """Globally block or unblock a user."""
    SETGLOBALACCOUNTSTATUS = "setglobalaccountstatus"
    """Hide or lock (or unhide or unlock) a global user account."""
    DELETEGLOBALACCOUNT = "deleteglobalaccount"
    """Delete a global user."""
    CREATELOCALACCOUNT = "createlocalaccount"
    """Forcibly create a local account."""

    # File Operations
    UPLOAD = "upload"
    """Upload a file, or get the status of pending uploads."""
    FILEREVERT = "filerevert"
    """Revert a file to an old version."""
    IMPORT = "import"
    """Import a page from another wiki, or from an XML file."""

    # Search & Discovery
    OPENSEARCH = "opensearch"
    """Search the wiki using the OpenSearch protocol."""
    LANGUAGESEARCH = "languagesearch"
    """Search for language names in any script."""

    # Communication & Notifications
    EMAILUSER = "emailuser"
    """Email a user."""
    THANK = "thank"
    """Send a thank-you notification to an editor."""
    WIKILOVE = "wikilove"
    """Give WikiLove to another user."""
    ECHOCREATEEVENT = "echocreateevent"
    """Manually trigger a notification to a user."""
    ECHOMARKREAD = "echomarkread"
    """Mark notifications as read for the current user."""
    ECHOMARKSEEN = "echomarkseen"
    """Mark notifications as seen for the current user."""
    ECHOMUTE = "echomute"
    """Mute or unmute notifications from certain users or pages."""

    # Content Transformation
    EXPANDTEMPLATES = "expandtemplates"
    """Expands all templates within wikitext."""
    CHANGECONTENTMODEL = "changecontentmodel"
    """Change the content model of a page."""
    SETPAGELANGUAGE = "setpagelanguage"
    """Change the language of a page."""

    # Watchlist
    WATCH = "watch"
    """Add or remove pages from the current user's watchlist."""
    FEEDWATCHLIST = "feedwatchlist"
    """Returns a watchlist feed."""

    # Feeds
    FEATUREDFEED = "featuredfeed"
    """Returns a featured content feed."""
    FEEDCONTRIBUTIONS = "feedcontributions"
    """Returns a user's contributions feed."""
    FEEDRECENTCHANGES = "feedrecentchanges"
    """Returns a recent changes feed."""
    FEEDTHREADS = "feedthreads"
    """Return a feed of discussion threads."""

    # Tags & Categories
    MANAGETAGS = "managetags"
    """Perform management tasks relating to change tags."""
    TAG = "tag"
    """Add or remove change tags from individual revisions or log entries."""

    # Security & Anti-Abuse
    ANTISPOOF = "antispoof"
    """Check a username against AntiSpoof's normalisation checks."""
    SPAMBLACKLIST = "spamblacklist"
    """Validate one or more URLs against the spam block list."""
    TITLEBLACKLIST = "titleblacklist"
    """Validate a page title, filename, or username against the TitleBlacklist."""
    TORBLOCK = "torblock"
    """Check if an IP address is blocked as a Tor exit node."""
    ABUSEFILTERCHECKMATCH = "abusefiltercheckmatch"
    """Check to see if an AbuseFilter matches a set of variables."""
    ABUSEFILTERCHECKSYNTAX = "abusefilterchecksyntax"
    """Check syntax of an AbuseFilter filter."""
    ABUSEFILTEREVALEXPRESSION = "abusefilterevalexpression"
    """Evaluates an AbuseFilter expression."""
    ABUSEFILTERUNBLOCKAUTOPROMOTE = "abusefilterunblockautopromote"
    """Unblocks a user from receiving autopromotions."""
    ABUSELOGPRIVATEDETAILS = "abuselogprivatedetails"
    """View private details of an AbuseLog entry."""

    # Translation & Localization
    SEARCHTRANSLATIONS = "searchtranslations"
    """Search translations."""
    TRANSLATIONAIDS = "translationaids"
    """Query all translations aids."""
    TRANSLATIONREVIEW = "translationreview"
    """Mark translations reviewed."""
    TRANSLATIONSTATS = "translationstats"
    """Fetch translation statistics."""
    TTMSERVER = "ttmserver"
    """Query suggestions from translation memories."""
    MARKFORTRANSLATION = "markfortranslation"
    """Mark a page for translation."""
    AGGREGATEGROUPS = "aggregategroups"
    """Manage aggregate message groups."""
    GROUPREVIEW = "groupreview"
    """Set message group workflow states."""

    # Structured Discussions (Flow)
    FLOW = "flow"
    """Allows actions to be taken on Structured Discussions pages."""
    FLOW_PARSOID_UTILS = "flow-parsoid-utils"
    """Convert text between wikitext and HTML."""
    FLOWTHANK = "flowthank"
    """Send a public thank-you notification for a Flow comment."""
    DISCUSSIONTOOLSEDIT = "discussiontoolsedit"
    """Post a message on a discussion page."""
    DISCUSSIONTOOLSFINDCOMMENT = "discussiontoolsfindcomment"
    """Find a comment by its ID or name."""
    DISCUSSIONTOOLSGETSUBSCRIPTIONS = "discussiontoolsgetsubscriptions"
    """Get subscription statuses of topics."""
    DISCUSSIONTOOLSSUBSCRIBE = "discussiontoolssubscribe"
    """Subscribe/unsubscribe to receive topic notifications."""
    DISCUSSIONTOOLSTHANK = "discussiontoolsthank"
    """Send a public thank-you notification for a comment."""
    THREADACTION = "threadaction"
    """Allows actions to be taken on threads and posts in threaded discussions."""

    # Mass Operations
    MASSMESSAGE = "massmessage"
    """Send a message to a list of pages."""
    EDITMASSMESSAGELIST = "editmassmessagelist"
    """Edit a mass message delivery list."""
    NEWSLETTERSUBSCRIBE = "newslettersubscribe"
    """Subscribe to or unsubscribe from a newsletter."""

    # System & Administrative
    HELP = "help"
    """Default. Display help for the specified modules."""
    PARAMINFO = "paraminfo"
    """Obtain information about API modules."""
    CHECKTOKEN = "checktoken"
    """Check the validity of a token from action=query&meta=tokens."""
    RSD = "rsd"
    """Export an RSD (Really Simple Discovery) schema."""
    SITEMATRIX = "sitematrix"
    """Get Wikimedia sites list."""
    STREAMCONFIGS = "streamconfigs"
    """Exposes event stream config."""
    WEBAPP_MANIFEST = "webapp-manifest"
    """Returns a webapp manifest."""
    TEMPLATEDATA = "templatedata"
    """Fetch data stored by the TemplateData extension."""
    JSONCONFIG = "jsonconfig"
    """Allows direct access to JsonConfig subsystem."""
    SHORTENURL = "shortenurl"
    """Shorten a long URL into a shorter one."""
    MERGEHISTORY = "mergehistory"
    """Merge page histories."""

    # Central Auth & Global Operations
    CENTRALAUTHTOKEN = "centralauthtoken"
    """Fetch a centralauthtoken for making authenticated requests."""
    CENTRALNOTICECDNCACHEUPDATEBANNER = "centralnoticecdncacheupdatebanner"
    """Request purge of banner content in CDN cache."""
    CENTRALNOTICECHOICEDATA = "centralnoticechoicedata"
    """Get data needed to choose a banner for given project/language."""
    CENTRALNOTICEQUERYCAMPAIGN = "centralnoticequerycampaign"
    """Get all configuration settings for a campaign."""

    # Community Configuration
    COMMUNITYCONFIGURATIONEDIT = "communityconfigurationedit"
    """Change content of a configuration provider."""

    # Voting & Polls
    STRIKEVOTE = "strikevote"
    """Allows admins to strike or unstrike a vote."""

    # Temporary Users
    ACQUIRETEMPUSERNAME = "acquiretempusername"
    """Acquire a temporary user username and stash it in session."""

    # Media & Transcoding
    TRANSCODERESET = "transcodereset"
    """Users with 'transcode-reset' right can reset and re-run transcode job."""
    IMAGEROTATE = "imagerotate"
    """This module has been disabled."""

    # Two-Factor Authentication
    WEBAUTHN = "webauthn"
    """API Module for server-client communication during registration/authentication."""

    # Internal Modules (typically not used directly)
    BOUNCEHANDLER = "bouncehandler"
    """Internal. Receive a bounce email and process it."""
    CATEGORYTREE = "categorytree"
    """Internal. Internal module for the CategoryTree extension."""
    CHARTINFO = "chartinfo"
    """Internal. Retrieve current count of unique Chart page usages."""
    CIRRUS_CHECK_SANITY = "cirrus-check-sanity"
    """Internal. Reports on correctness of page ids in search index."""
    CIRRUS_CONFIG_DUMP = "cirrus-config-dump"
    """Internal. Dump of CirrusSearch configuration."""
    CIRRUS_MAPPING_DUMP = "cirrus-mapping-dump"
    """Internal. Dump of CirrusSearch mapping for this wiki."""
    CIRRUS_PROFILES_DUMP = "cirrus-profiles-dump"
    """Internal. Dump of CirrusSearch profiles for this wiki."""
    CIRRUS_SETTINGS_DUMP = "cirrus-settings-dump"
    """Internal. Dump of CirrusSearch settings for this wiki."""
    COLLECTION = "collection"
    """Internal. API module for performing various operations on collections."""
    CSPREPORT = "cspreport"
    """Internal. Used by browsers to report CSP violations."""
    DISCUSSIONTOOLSCOMPARE = "discussiontoolscompare"
    """Internal. Get info about comment changes between revisions."""
    DISCUSSIONTOOLSPAGEINFO = "discussiontoolspageinfo"
    """Internal. Returns metadata for discussion tools."""
    DISCUSSIONTOOLSPREVIEW = "discussiontoolspreview"
    """Internal. Preview a message on a discussion page."""
    EDITCHECKREFERENCEURL = "editcheckreferenceurl"
    """Internal. Check the status of a URL for use as reference."""
    FANCYCAPTCHARELOAD = "fancycaptchareload"
    """Internal. Get a new FancyCaptcha."""
    JSONDATA = "jsondata"
    """Internal. Retrieve localized JSON data."""
    JSONTRANSFORM = "jsontransform"
    """Internal. Retrieve JSON data transformed by a Lua function."""
    MANAGEGROUPSYNCHRONIZATIONCACHE = "managegroupsynchronizationcache"
    """Internal. Manage group sync cache."""
    MANAGEMESSAGEGROUPS = "managemessagegroups"
    """Internal. Add message as rename/new message during imports."""
    MESSAGEGROUPSUBSCRIPTION = "messagegroupsubscription"
    """Internal. Message group subscription operations."""
    OATHVALIDATE = "oathvalidate"
    """Internal. Validate a two-factor authentication (OATH) token."""
    PARSER_MIGRATION = "parser-migration"
    """Internal. Parse a page with two different parser configurations."""
    READINGLISTS = "readinglists"
    """Internal. Reading list write operations."""
    SANITIZE_MAPDATA = "sanitize-mapdata"
    """Internal. Performs data validation for Kartographer extension."""
    SCRIBUNTO_CONSOLE = "scribunto-console"
    """Internal. Internal module for servicing XHR requests from Scribunto console."""
    SECUREPOLLAUTH = "securepollauth"
    """Internal. Allows remote wiki to authenticate users before voting."""
    STASHEDIT = "stashedit"
    """Internal. Prepare an edit in shared cache."""
    TIMEDTEXT = "timedtext"
    """Internal. Provides timed text content for usage by <track> elements."""
    TRANSLATIONCHECK = "translationcheck"
    """Internal. Validate translations."""
    TRANSLATIONENTITYSEARCH = "translationentitysearch"
    """Internal. Search for message groups and messages."""
    ULSLOCALIZATION = "ulslocalization"
    """Internal. Get the localization of ULS in the given language."""
    ULSSETLANG = "ulssetlang"
    """Internal. Update user's preferred interface language."""
    VISUALEDITOR = "visualeditor"
    """Internal. Returns HTML5 for a page from the Parsoid service."""
    VISUALEDITOREDIT = "visualeditoredit"
    """Internal. Save an HTML5 page to MediaWiki via Parsoid service."""
    WIKIMEDIAEVENTSBLOCKEDEDIT = "wikimediaeventsblockededit"
    """Internal. Log information about blocked edit attempts."""
