"""
Provides object relationship management for wiki data.
"""
from sharp.collections import KeyedCollection
from wiki.data.common import Namespaces
from wiki.data.title import Title
from wiki.data.namespaces import Namespace
from .article import Article
from .wiki_collection import ArticleCollection

# Top-Level Modding Category.
# https://starfieldwiki.net/wiki/Category:Starfield_Mod

# For documenting released mods
# https://starfieldwiki.net/wiki/Starfield_Mod:Mods
# https://starfieldwiki.net/wiki/Category:Starfield_Mod-Mods

# For topics on mod creation
# https://starfieldwiki.net/wiki/Category:Starfield_Mod-Modding

class Wiki:
    """
    Used to manage wiki pages.
    Provides onstants for the UESP Wiki.
    This class contains constants that are used throughout the wiki generation process.
    These fields should be considered TODO for implementating with configurable options.
    """


    # Namespaces
    #---------------------------------------------

    NAMESPACE_MODDING:Namespace = Namespace("Starfield_Mod", "SFM")
    """
    The top-level namespace for modding related articles.
    This is used within page content to categorize articles related to modding.

    This DOES have internal link syntax.
    ex: `[[SFM:Script-MyScript]]`

    https://starfieldwiki.net/wiki/Starfield_Mod:Main_Page
    """


    # Categories
    #---------------------------------------------

    CATEGORY_TEMPLATES_INFOBOX:Title = Title("Infobox_Templates", Namespaces.Category)
    """
    The category for article-templates that provide information boxes.
    This string is used in the template definition directly and does not have internal link syntax.
    """


    CATEGORY_PAPYRUS:Title = Title("Starfield_Mod-Papyrus", Namespaces.Category)
    """
    The category for Papyrus scripts and related articles.
    This is used within page content to categorize articles related to Papyrus scripts.
    This DOES have internal link syntax.

    ex: `[[Category:Starfield_Mod-Papyrus]]`
    """


    def __init__(self) -> None:
        super().__init__()
        # self.namespaces:NamespaceCollection = NamespaceCollection()
        # """A dictionary of all recognized namespaces by their names."""

        self.titles:KeyedCollection[str, Title] = KeyedCollection(key_extract=lambda item: item.value)

        self.articles:ArticleCollection = ArticleCollection()
        """A dictionary of wiki articles indexed by their titles."""


    @staticmethod
    def create() -> 'Wiki':
        this:Wiki = Wiki()

        category_papyrus_documentation_automated:Title = Title("Papyrus_Documentation_Automated", Namespaces.Category)
        category_papyrus_documentation_automated_article:Article = Article(category_papyrus_documentation_automated)
        category_papyrus_documentation_automated_article.content = [
            "This category contains all pages that were automatically generated by the Scribe Bot.",
            "",
            "These pages are created to document Papyrus scripts and their members for modding purposes.",
            "Please do not edit these pages directly, as they may be overwritten by future bot runs."
        ]
        this.articles.add(category_papyrus_documentation_automated_article)


        category_SFM:Article = Article(Title("Starfield_Mod", Namespaces.Category))
        this.articles.add(category_SFM)

        category_SFM_Papyrus:Article = Article(Title("Starfield_Mod-Papyrus", Namespaces.Category))
        category_SFM_Papyrus.categories.append(category_SFM.title)
        this.articles.add(category_SFM_Papyrus)

        category_SFM_Scripts:Article = Article(Title("Starfield_Mod-Scripts", Namespaces.Category))
        category_SFM_Scripts.categories.append(category_SFM.title)
        this.articles.add(category_SFM_Scripts)

        script_object_summary:Article = Article(Title("Script_Object_Summary", Namespaces.Template))
        script_object_summary.categories.append(Wiki.CATEGORY_TEMPLATES_INFOBOX)
        this.articles.add(script_object_summary)

        user_page:Article = Article(Title("Scrivener07", Namespaces.User)) # This is for debug purposes.
        user_page.content = ["My name is Scrivener and I have been modding since TES4 Oblivion."]
        this.articles.add(user_page)

        bot_page:Article = Article(Title("Scrivener07/Bot", Namespaces.User)) # This is for debug purposes.
        bot_page.content = ["This is the Scribe Bot wiki page."]
        this.articles.add(bot_page)

        return this


    # Methods
    #---------------------------------------------

    @staticmethod
    def link_script_object(script_name:str) -> str:
        """Return a MediaWiki link for script object page."""
        return f"[[SFM:Script-{script_name}|{script_name}]]"


    @staticmethod
    def link_script_member(script_name:str, member_name:str) -> str:
        """Return a MediaWiki link for a script member page."""
        return f"[[SFM:Script-{script_name}/{member_name}|{member_name}]]"
