"""
Used to generate wiki page content.
"""
import logging
import os
from papyrus.project import PapyrusProject
from papyrus.code import Member
from wiki.data.common import Namespaces
from scribe.app.log import Log
from scribe.app.context import AppContext
from scribe.assets.papyrus import PapyrusPackage, PapyrusTarget
from scribe.composer.article import Article
from scribe.composer.builder import ArticleBuilder
from scribe.composer.wiki import Wiki
from scribe.generators.pages_index import PageIndex
from scribe.generators.pages_member import PageMember
from scribe.generators.pages_script import PageScript
from scribe.services.composer import ComposerService
from scribe.services.papyrus import PapyrusService
from wiki.data.title import Title

class GeneratorService:
    """
    The service responsible for generating wiki pages from Papyrus projects.
    """

    NAME:str = "Generator"
    """The name of this service."""

    PAGE_SCRIPT_INDEX_FILE_NAME:str = "Script_Information.wiki"
    """The file name of the wiki page that summarizes all scripts in a Papyrus project."""


    @staticmethod
    def start(app:AppContext) -> bool:
        logging.info(f" {GeneratorService.NAME} ".center(Log.DIV_WIDTH, "-"))

        # Startup the required services.
        try:
            papyrus:PapyrusService = PapyrusService.create(app.configuration)
        except Exception as exception:
            logging.error(f"Aborting program. Failed to start Papyrus service. {exception}")
            return False

        try:
            composer:ComposerService = ComposerService.create(app.configuration)
        except Exception as exception:
            logging.error(f"Aborting program. Failed to start composer service. {exception}")
            return False

        # Start the composer service.
        logging.info("Wiki Generation ".center(Log.DIV_WIDTH, "-"))
        logging.info(f"Writing wiki pages for {len(papyrus.packages)} Papyrus packages.")

        user_page:Article = Article(Title("Scrivener07", Namespaces.User))
        user_page.content = ["My name is Scrivener and I have been modding since TES4 Oblivion."]
        composer.articles.add(user_page)

        bot_page:Article = Article(Title("Scribe-Bot", Namespaces.User))
        bot_page.content = ["This is the Scribe Bot wiki page."]
        composer.articles.add(bot_page)

        category_papyrus_documentation_automated:Article = Article(Title("Papyrus_Documentation_Automated", Namespaces.Category))
        category_papyrus_documentation_automated.content = [
            "This category contains all pages that were automatically generated by the Scribe Bot.",
            "",
            "These pages are created to document Papyrus scripts and their members for modding purposes.",
            "Please do not edit these pages directly, as they may be overwritten by future bot runs."
        ]
        composer.articles.add(category_papyrus_documentation_automated)


        category_SFM:Article = Article(Wiki.SFM_CATEGORY)
        category_SFM.content = [
            "This category contains all pages related to Starfield modding.",
            "It is used to categorize articles related to modding and Papyrus scripts."
        ]
        composer.articles.add(category_SFM)

        category_SFM_Papyrus:Article = Article(Wiki.PAPYRUS_CATEGORY)
        category_SFM_Papyrus.categories.append(category_SFM.title)
        composer.articles.add(category_SFM_Papyrus)

        category_SFM_Scripts:Article = Article(Title("Starfield_Mod-Scripts", Namespaces.Category))
        category_SFM_Scripts.categories.append(category_SFM.title)
        composer.articles.add(category_SFM_Scripts)

        script_object_summary:Article = Article(Title("Script_Object_Summary", Namespaces.Template))
        script_object_summary.categories.append(Wiki.INFOBOX_TEMPLATES_CATEGORY)
        composer.articles.add(script_object_summary)

        # Generate wiki pages for each project.
        for package_key in papyrus.packages:
            package:PapyrusPackage = papyrus.packages[package_key]
            GeneratorService.wiki_package(composer, papyrus, package)

        # Generate the wiki index summary page.
        article:Article = PageIndex.create(papyrus, composer)
        composer.articles.add(article)

        # Save all generated wiki pages to disk.
        composer.save()
        return True


    # Generate
    #---------------------------------------------

    @staticmethod
    def wiki_package(composer:ComposerService, papyrus:PapyrusService, package:PapyrusPackage) -> None:
        package_category:Article = GeneratorService.new_package_category(composer, package)
        composer.articles.add(package_category)

        package_page:Article = GeneratorService.new_package_page(composer, package)
        package_page.categories.append(package_category.title)
        composer.articles.add(package_page)

        for target_key in package.targets:
            target:PapyrusTarget = package.targets[target_key]
            if not GeneratorService.wiki_project(composer, papyrus, target):
                logging.error(f"[{target.identifier}] Failed to generate one or more wiki pages.")


    @staticmethod
    def wiki_project(composer:ComposerService, papyrus:PapyrusService, target:PapyrusTarget) -> bool:
        # Skip any disabled projects.
        if not target.publish.enable:
            logging.info(f"[{target.identifier}] has disabled publishing. Skipping wiki page generation.")
            return True # Not an error, successfully did nothing.

        project:PapyrusProject|None = papyrus.client.projects.get(target.identifier)
        if not project:
            logging.warning(f"[{target.identifier}] Skipping this publish target. No matching Papyrus project was found in the Papyrus context.")
            return False

        # Validate provided project configuration.
        if not project.root:
            logging.warning(f"[{project.identifier}] Skipping this Papyrus project. The project `root` directory was not set.")
            return False

        # Ensure the project input directory exist, else skip.
        if not os.path.exists(project.root):
            logging.warning(f"[{project.identifier}] Skipping this Papyrus project. The project `root` directory does not exist: '{project.root}'")
            return False

        # Wiki: Generate wiki pages for each project script.
        for script in project.scripts:
            # Write a wiki page for this script object.
            if target.publish.enable_objects:
                script_page:Article = PageScript.create(composer, papyrus.client, project, script)
                composer.articles.add(script_page)

            # Write a wiki page for this script member.
            if target.publish.enable_members:
                for key in script.members:
                    member:Member = script.members[key]
                    script_member_page:Article = PageMember.create(composer, script, member)
                    composer.articles.add(script_member_page)

        return True


    # Composer
    #---------------------------------------------

    @staticmethod
    def new_package_category(composer:ComposerService, package:PapyrusPackage) -> Article:
        builder:ArticleBuilder = ArticleBuilder(composer)
        builder.title(package.name, Namespaces.Category)
        builder.category(Wiki.PAPYRUS_CATEGORY)
        return builder.build()


    @staticmethod
    def new_package_page(composer:ComposerService, package:PapyrusPackage) -> Article:
        builder:ArticleBuilder = ArticleBuilder(composer)
        builder.title(package.name, Wiki.SFM_NAMESPACE)
        builder.category(Wiki.PAPYRUS_CATEGORY)
        builder.line(f"== Details ==\n")
        builder.line(f"* '''Name''': {package.name}\n")
        builder.line(f"* '''Author''': {package.author}\n")
        builder.line(f"* '''Description''': {package.description}\n")
        builder.line(f"* '''Platform''': {package.platform}\n")
        builder.line(f"* '''URL''': {package.url}\n")
        builder.line(f"* '''URL ID''': {package.url_id}\n")
        builder.line(f"* '''Version''': {package.version}\n")
        builder.line(f"* '''Version Build''': {package.version_build}\n")
        builder.line(f"* '''Version Date''': {package.version_date}\n")
        return builder.build()
