[project]
name = "wiki"
version = "0.0.1"
description = "Provides methods for interacting with MediaWiki."
requires-python = ">=3.13"
dependencies = [
    "requests>=2.25.0"
]


[tool.setuptools.packages.find]
where = ["."]


[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
